Issue 12: Migrating pravega operator charts source code
pravega/charts pull request #13
Opened 2021-07-07 13:01 UTC by SrishT

Signed-off-by: SrishT <Srishti.Thakkar@dell.com>

### Change log description
Moves the source code of the charts that were placed within the pravega operator repository into this repository.

### Purpose of the change
Fixes #12 

### How to verify it
Following the steps mentioned in the README should install the pravega operator and pravega successfully.

2021-07-08 09:21 UTC, anishakj requested changes
Changes are looking good,  have seen links are broken at some palces. Could you please fix those?

2021-07-08 09:24 UTC, anishakj commented on charts/pravega-operator/README.md
> +
correct the link

2021-07-08 09:24 UTC, anishakj commented on charts/pravega-operator/README.md
> +For upgrading pravega-operator, please refer [upgrade guide](../../doc/operator-upgrade.md)
correct the link

2021-07-14 12:33 UTC, SrishT commented on charts/pravega-operator/README.md
> +
done

2021-07-14 12:34 UTC, SrishT commented on charts/pravega-operator/README.md
> +For upgrading pravega-operator, please refer [upgrade guide](../../doc/operator-upgrade.md)
done

2021-07-14 12:34 UTC, SrishT commented on charts/pravega-operator/README.md
> +  - An Issuer and a Certificate (either self-signed or CA signed) in the same namespace that the Pravega Operator will be installed (refer to [this certificate.yaml file](../../deploy/certificate.yam
done

2021-07-14 12:57 UTC, anishakj approved these changes
LGTM

2021-07-14 12:58 UTC, merged